export enum CustomersActionTypes {
  API_RESPONSE_SUCCESS = '@@customers/API_RESPONSE_SUCCESS',
  API_RESPONSE_ERROR = '@@customers/API_RESPONSE_ERROR',

  SET_CUSTOMER = '@@customers/SET_CUSTOMER',
  SET_CUSTOMERS = '@@customers/SET_CUSTOMERS',
  CLEAN_CUSTOMERS = '@@customers/CLEAN_CUSTOMERS',
  GET_ALL_CUSTOMERS_SAGA = '@@customers/GET_ALL_CUSTOMERS_SAGA',
  GET_CUSTOMER_SAGA = '@@customers/GET_CUSTOMER_SAGA',
  POST_CUSTOMER_SAGA = '@@customers/POST_CUSTOMER_SAGA',
  REMOVE_CUSTOMER_SAGA = '@@customers/REMOVE_CUSTOMER_SAGA'
}
